### ISSUE TITLE
Not centering the header

### ISSUE THREAD

**Issue by john482847573** [dundalek/userstyles#2]
![image](https://user-images.githubusercontent.com/92234562/232941340-bca03381-3799-44b8-90d1-df9abb256cfd.png)
Is what it shows when the userstyle is installed.

**Comment by dundalek** [comment]
Hi, I gave up on the centering, it would be too much effort to keep up with the style changes. I will need to update screenshots.

**Comment by dundalek** [comment]
Did another Github update and updated screenshots to reflect that header is not centered anymore.

**Comment by dundalek** [comment]
As a compromise I was able to center the inner part of the header:

![image](https://github.com/dundalek/userstyles/assets/755611/c735fee3-2daa-4a5f-82f6-a5015af9d3a3)
